FROM conda/miniconda3

conda update conda \
    && conda install -y mkl \
    && conda install -y faiss-cpu \
    && conda install -y flask \
    && conda install -y redis \
    && conda install -y uwsgi \
    && conda install -y flask_wtf \
